repos:
  # Ruff linter and formatter (replaces Black, isort, Flake8, etc.)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      # Run the linter with auto-fixes
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # Mypy type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: [numpy>=1.20.0]
        args: [--ignore-missing-imports]

  # General file quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
